server:
  port: 9094
  
spring:
  application:
    name: microservice-zuul

zuul:
  routes:
    cadastro:
      path: /api/cadastro/**
      url: http://localhost:9095/api/cadastro
    auth:
      path: /api/auth/**
      url: http://localhost:9095/api/auth
